### ISSUE TITLE
Wrong CheckDigit Calculation

### ISSUE THREAD

**Issue by rvalle** [wankdanker/gs1#2]
I was writing some unit tests before using this GS1 library.

I noticed that some CheckDigits are not been calculated properly.

I believe the function checkdigit returns 10 when it should return 0.

In particular, I think the following test should pass and fails:

```
   it("Will Test CheckDigit Calculation",()=>{
        var cd=gs1.checkdigit("735010516082");
        assert.equal(cd,0);
    });
```
for the example above checkdigit is returning 10 and it should return 0.

**Comment by wankdanker** [comment]
This was fixed in #3.
